### PR TITLE
Update ENRICH 2023 photos

### PR DESCRIPTION
**Pull request by nathan-gt**

### CODE REVIEW

**Comment by Leuchak** [comment]
the files are too big for the web (~30Mb).
ideally, each file should be less than 750kb in size.

the avif format is now supported by all browsers, so I recommend converting to this format. The quality will be maximum and the size minimum. You can also keep them in webp or jpg with stronger compression or webp at the expense of quality but it won't be too noticeable.

**Comment by Leuchak** [comment]
do you want me to do it?

**Comment by McCaroon** [comment]
I have to agree with @Leuchak, a quick change to .avif then let's merge! ;)

**Comment by Leuchak** [comment]
I resized the images and converted them to avif. From 42MB to 716K in total. Visual quality is indistinguishable.

**Comment by McCaroon** [comment]
Ready to go ! 👌

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by Leuchak — APPROVED** [review]

**Pull request merged**
